export interface Project {
  id: string;
  slug: string;
  title: string;
  description: string;
  descriptionEs?: string;
  category: string;
  categoryEs?: string;
  image: string;
  video?: string;
  url: string;
  year: number;
  technologies: string[];
  featured?: boolean;
  color?: string;
}

export const PLACEHOLDER_IMAGE = "/projects/placeholder.webp";
const TBD_DESC_EN = "Case study coming soon.";
const TBD_DESC_ES = "Case study próximamente.";

export const projects: Project[] = [
  {
    id: "nautirent",
    slug: "nautirent",
    title: "Nautirent",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Web Application",
    categoryEs: "Aplicación Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0f172a",
  },
  {
    id: "fang-tours",
    slug: "fang-tours",
    title: "Fang Tours",
    description:
      "Booking platform with interactive calendar, payment gateway, and real-time tour management.",
    descriptionEs:
      "Plataforma de reservas con calendario interactivo, pasarela de pago y gestión de tours en tiempo real.",
    category: "Web Application",
    categoryEs: "Aplicación Web",
    image: "/projects/fang-tours.webp",
    video: "/projects_video/fang-tours.webm",
    url: "#",
    year: 2024,
    technologies: ["Next.js", "Supabase", "Stripe"],
    featured: true,
    color: "#1c1917",
  },
  {
    id: "fase",
    slug: "fase",
    title: "Fase",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/fase.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0c0a09",
  },
  {
    id: "samoa",
    slug: "samoa",
    title: "Samoa",
    description:
      "Full brand identity from scratch: naming, logo, menu design, website with reservations, and social launch strategy.",
    descriptionEs:
      "Identidad de marca completa desde cero: naming, logo, diseño de carta, web con reservas y estrategia de lanzamiento en redes.",
    category: "Branding",
    categoryEs: "Branding",
    image: "/projects/samoa.webp",
    video: "/projects_video/samoa.webm",
    url: "#",
    year: 2024,
    technologies: ["Next.js", "Tailwind", "Figma"],
    featured: true,
    color: "#1a1a2e",
  },
  {
    id: "musa",
    slug: "musa",
    title: "Musa",
    description:
      "Sensory restaurant website with integrated booking, interactive menu, and local SEO. Online reservations up 40%.",
    descriptionEs:
      "Web sensorial para restaurante con reservas integradas, menú interactivo y SEO local. Reservas online +40%.",
    category: "Website",
    categoryEs: "Web",
    image: "/projects/musa.webp",
    video: "/projects_video/musa-pot.webm",
    url: "#",
    year: 2024,
    technologies: ["Next.js", "GSAP", "Three.js"],
    featured: true,
    color: "#0f172a",
  },
  {
    id: "patricia-avendano",
    slug: "patricia-avendano",
    title: "Patricia Avendaño",
    description:
      "Bilingual fashion designer website with interactive lookbook, fullscreen runway videos, and press section.",
    descriptionEs:
      "Web bilingüe para diseñadora de moda con lookbook interactivo, vídeos de pasarela a pantalla completa y sección de prensa.",
    category: "Website",
    categoryEs: "Web",
    image: "/projects/patricia-avendano.webp",
    video: "/projects_video/patricia-avendano.webm",
    url: "#",
    year: 2024,
    technologies: ["Next.js", "Framer Motion", "i18n"],
    featured: true,
    color: "#171717",
  },
  {
    id: "cliche",
    slug: "cliche",
    title: "CLICHÉ",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/cliche.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#1a1a2e",
  },
  {
    id: "kairos-futures",
    slug: "kairos-futures",
    title: "Kairos Futures",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/kairos.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#111827",
  },
  {
    id: "true-trading-app",
    slug: "true-trading-app",
    title: "True Trading App",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Web Application",
    categoryEs: "Aplicación Web",
    image: "/projects/truetrading.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#18181b",
  },
  {
    id: "pbb-porrino",
    slug: "pbb-porrino",
    title: "Porriño Baloncesto Base",
    description:
      "Full digital presence for a local business: website, booking system, and local SEO strategy driving consistent organic traffic.",
    descriptionEs:
      "Presencia digital completa para negocio local: web, sistema de reservas y estrategia SEO local que genera tráfico orgánico constante.",
    category: "Website",
    categoryEs: "Web",
    image: "/projects/pbb-porrino.webp",
    video: "/projects_video/pbb-porrino.webm",
    url: "#",
    year: 2025,
    technologies: ["Next.js", "Tailwind", "SEO"],
    featured: true,
    color: "#0a0a0a",
  },
  {
    id: "canelita",
    slug: "canelita",
    title: "Canelita Tienda de Ropa",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "E-commerce",
    categoryEs: "E-commerce",
    image: "/projects/canelita.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#171717",
  },
  {
    id: "cerveceria-equs",
    slug: "cerveceria-equs",
    title: "Cervecería Equs",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/equs.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#1c1917",
  },
  {
    id: "autoescuela-gti",
    slug: "autoescuela-gti",
    title: "Autoescuela GTI",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/autoescuelagti.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0a0a0a",
  },
  {
    id: "nabi",
    slug: "nabi",
    title: "Nabi",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "E-commerce",
    categoryEs: "E-commerce",
    image: "/projects/nabi.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#18181b",
  },
  {
    id: "licentia",
    slug: "licentia",
    title: "Licentia",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/licentia.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0c0a09",
  },
  {
    id: "pro-lift-formacion",
    slug: "pro-lift-formacion",
    title: "Formación PRO Lift",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0f172a",
  },
  {
    id: "fisioterapia-noia",
    slug: "fisioterapia-noia",
    title: "Fisioterapia Noia",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/fisionorte.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#111827",
  },
  {
    id: "cachadas",
    slug: "cachadas",
    title: "Cachadas",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "E-commerce",
    categoryEs: "E-commerce",
    image: "/projects/cachadas.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#1a1a2e",
  },
  {
    id: "ticketera-la-fabrica",
    slug: "ticketera-la-fabrica",
    title: "Ticketera La Fábrica",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Web Application",
    categoryEs: "Aplicación Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0a0a0a",
  },
  {
    id: "true-trading-landing",
    slug: "true-trading-landing",
    title: "True Trading Landing",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Landing Page",
    categoryEs: "Landing Page",
    image: "/projects/truetrading.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#18181b",
  },
  {
    id: "lift",
    slug: "lift",
    title: "Lift",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#18181b",
  },
  {
    id: "ratsquad",
    slug: "ratsquad",
    title: "Ratsquad",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#1c1917",
  },
  {
    id: "marisa-gamez",
    slug: "marisa-gamez",
    title: "Marisa Gámez",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0f172a",
  },
  {
    id: "paris-de-noia",
    slug: "paris-de-noia",
    title: "París de Noia",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/parisdenoia.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#0c0a09",
  },
  {
    id: "roots",
    slug: "roots",
    title: "Roots",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/roots.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#171717",
  },
  {
    id: "ertuned",
    slug: "ertuned",
    title: "ERTuned",
    description: TBD_DESC_EN,
    descriptionEs: TBD_DESC_ES,
    category: "Website",
    categoryEs: "Web",
    image: "/projects/ertuned.webp",
    url: "#",
    year: 2024,
    technologies: ["TBD"],
    color: "#1a1a2e",
  },
  {
    id: "timetracker",
    slug: "timetracker",
    title: "Timetracker",
    description:
      "Custom SaaS for an industrial SME to fully digitize employee time tracking.",
    descriptionEs:
      "Software a medida para una PYME que buscaba la gestión completamente digital de las horas de sus empleados.",
    category: "Web Application",
    categoryEs: "Aplicación Web",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2023,
    technologies: ["React", "Node.js", "Mobile App"],
    color: "#0a0a0a",
  },
  {
    id: "xaulabs",
    slug: "xaulabs",
    title: "XauLabs",
    description:
      "Cross-platform iOS and Android app gamifying the trader learning journey.",
    descriptionEs:
      "Aplicación multiplataforma para iOS y Android que busca gamificar el proceso de aprendizaje en el mundo del trader.",
    category: "Mobile App",
    categoryEs: "Aplicación Móvil",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2023,
    technologies: ["React Native", "iOS", "Android"],
    color: "#111827",
  },
  {
    id: "san-jose",
    slug: "san-jose",
    title: "San José",
    description: "Communication and management mobile app for an educational center.",
    descriptionEs: "App móvil de comunicación y gestión para centro educativo.",
    category: "Mobile App",
    categoryEs: "Aplicación Móvil",
    image: PLACEHOLDER_IMAGE,
    url: "#",
    year: 2023,
    technologies: ["Education", "Communication", "App"],
    color: "#0c0a09",
  },
  {
    id: "almudena-muhle",
    slug: "almudena-muhle",
    title: "Almudena Muhle",
    description:
      "Elegant website for an interior design studio, showcasing projects as immersive stories.",
    descriptionEs:
      "Web elegante para un estudio de diseño de interiores que presenta proyectos como historias inmersivas.",
    category: "Website",
    categoryEs: "Web",
    image: "/projects/almudena-muhle.webp",
    video: "/projects_video/almudena-muhle.webm",
    url: "#",
    year: 2025,
    technologies: ["Next.js", "GSAP", "Tailwind"],
    featured: true,
    color: "#111827",
  },
  {
    id: "koopey",
    slug: "koopey",
    title: "Koopey",
    description:
      "MVP for a peer-to-peer service exchange platform with profiles, matching, and chat.",
    descriptionEs:
      "MVP para una plataforma de intercambio de servicios entre particulares con perfiles, matching y chat.",
    category: "Platform",
    categoryEs: "Plataforma",
    image: "/projects/koopey.webp",
    video: "/projects_video/koopey.webm",
    url: "#",
    year: 2024,
    technologies: ["React", "Node.js", "WebSocket"],
    featured: true,
    color: "#0a0a0a",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
